import CalculateOutlined from '@mui/icons-material/CalculateOutlined'
import DataObjectRounded from '@mui/icons-material/DataObjectRounded'
import RefreshRounded from '@mui/icons-material/RefreshRounded'
import { Alert, Box, Button, Chip, FormControl, IconButton, InputLabel, LinearProgress, MenuItem, Select, Stack, Tab, Tabs, TextField, Tooltip, Typography } from '@mui/material'
import { useEffect, useMemo, useState } from 'react'
import { GeometryDetailDrawer } from '../components/common/GeometryDetailDrawer'
import { MapLegend } from '../components/common/MapLegend'
import { PageHeader } from '../components/common/PageHeader'
import { RunStateBadge } from '../components/common/RunStateBadge'
import { SurveyCanvas } from '../components/common/SurveyCanvas'
import { useAuth } from '../hooks/useAuth'
import { useCoverageLayers } from '../hooks/useCoverageLayers'
import { useCoverageGapStore, type GapScope } from '../stores/coverage-gap-store'
import { useSonarRunStore } from '../stores/sonar-run-store'
import { useSurveyAreaStore } from '../stores/survey-area-store'
import { GAP_DEADLINE_HOURS, formatRemaining } from '../utils/deadline'
import { GAP_SEVERITY_LABEL, GAP_STATE_LABEL, type GapState } from '../types/enums/gap-severity'

const nextGapStates:Partial<Record<GapState,GapState[]>>={detected:['reviewed'],reviewed:['accepted','false_positive'],accepted:['resurveyed'],false_positive:['closed'],resurveyed:['closed']}
export function CoveragePage(){const{user,hasRole}=useAuth();const areas=useSurveyAreaStore(state=>state.items);const fetchAreas=useSurveyAreaStore(state=>state.fetch);const runs=useSonarRunStore(state=>state.items);const fetchRuns=useSonarRunStore(state=>state.fetch);const{items,selected,evidence,loading,scope,setScope,fetch,select,detect,claim,release,transition}=useCoverageGapStore();const[areaID,setAreaID]=useState(1);const[runIDs,setRunIDs]=useState<number[]>([1]);const[resolution,setResolution]=useState(20);const[drawer,setDrawer]=useState(false);const[note,setNote]=useState('已核对坐标系、输入校验和与补测线建议，结论仅用于离线规划。');const[releaseNote,setReleaseNote]=useState('');const[releaseOpen,setReleaseOpen]=useState(false);const[,tick]=useState(0);useEffect(()=>{const timer=setInterval(()=>tick(value=>value+1),30_000);return()=>clearInterval(timer)},[]);useEffect(()=>{void Promise.all([fetch(),fetchAreas(),fetchRuns()])},[fetch,fetchAreas,fetchRuns]);useEffect(()=>{if(areas[0]&&!areas.some(area=>area.id===areaID))setAreaID(areas[0].id)},[areas,areaID]);useEffect(()=>{const eligible=runs.filter(run=>run.run_state==='processed'&&(run.transect_plan?.survey_area_id??0)===areaID).map(run=>run.id);if(eligible.length&&!runIDs.some(id=>eligible.includes(id)))setRunIDs([eligible[0]!])},[runs,areaID,runIDs]);const area=selected?.survey_area??areas.find(value=>value.id===(selected?.survey_area_id??areaID));const sourceRuns=selected?runs.filter(run=>selected.source_run_ids.includes(run.id)):runs.filter(run=>runIDs.includes(run.id));const plan=sourceRuns[0]?.transect_plan;const layers=useCoverageLayers(area,plan,sourceRuns,selected);const legends=useMemo(()=>layers.map(layer=>({label:layer.label,color:layer.color,pattern:layer.dash?'dash' as const:layer.fill?'fill' as const:'solid' as const})),[layers]);const calculate=async()=>detect({survey_area_id:areaID,source_run_ids:runIDs,algorithm_version:'grid-cover-v1.0.0',resolution_m:resolution});const eligibleRuns=runs.filter(run=>run.run_state==='processed'&&(run.transect_plan?.survey_area_id??0)===areaID);const canCalculate=hasRole('admin','data_processor');const canReview=hasRole('reviewer');const isMine=canReview&&!!selected?.assignee_id&&selected.assignee_id===user?.id;const isUnclaimed=!!selected&&selected.assignee_id==null&&selected.gap_state!=='closed';const deadline=selected?formatRemaining(selected.due_at):null;const confirmRelease=async()=>{await release(selected!,releaseNote.trim()?releaseNote:'复核员退回待认领池');setReleaseOpen(false);setReleaseNote('');await setScope('unclaimed')};return <>
  <PageHeader eyebrow="COVERAGE EVIDENCE REVIEW" title="覆盖分析" description="冻结测区与已处理航迹，计算覆盖、重复扫测和疑似缺口；严重 4 小时、主要 1 天、轻微 3 天内完成复核。" actions={<Tooltip title="刷新"><IconButton aria-label="刷新覆盖结果" onClick={()=>void Promise.all([fetch(),fetchRuns()])}><RefreshRounded/></IconButton></Tooltip>}/>{loading&&<LinearProgress/>}
  <Box className="coverage-controls"><Box><Typography variant="overline">NEW ANALYSIS</Typography><Typography variant="h6">冻结本次输入</Typography></Box><FormControl size="small" sx={{minWidth:180}}><InputLabel>测区</InputLabel><Select label="测区" value={areaID} onChange={event=>{setAreaID(Number(event.target.value));setRunIDs([])}}>{areas.map(area=><MenuItem value={area.id} key={area.id}>{area.area_code}</MenuItem>)}</Select></FormControl><FormControl size="small" sx={{minWidth:220}}><InputLabel>已处理运行</InputLabel><Select multiple label="已处理运行" value={runIDs} onChange={event=>setRunIDs((event.target.value as number[]))}>{eligibleRuns.map(run=><MenuItem value={run.id} key={run.id}>{run.run_code}</MenuItem>)}</Select></FormControl><TextField size="small" type="number" label="网格 (m)" value={resolution} onChange={event=>setResolution(Number(event.target.value))} sx={{width:120}}/>{canCalculate&&<Button variant="contained" startIcon={<CalculateOutlined/>} disabled={runIDs.length===0} onClick={()=>void calculate()}>计算覆盖</Button>}</Box>
  <Box className="coverage-workspace"><Box className="result-rail"><Box className="section-heading"><Typography variant="h6">缺口队列</Typography><Typography variant="caption">{items.length} 条</Typography></Box>{canReview&&<Tabs value={scope} onChange={(_,value:GapScope)=>void setScope(value)} variant="fullWidth" sx={{minHeight:36,mb:1,'& .MuiTab-root':{minHeight:36,fontSize:12}}}><Tab value="unclaimed" label="待认领"/><Tab value="mine" label="我的"/><Tab value="" label="全部"/></Tabs>}{items.map(item=>{const remain=formatRemaining(item.due_at);return <button type="button" key={item.id} className={selected?.id===item.id?'gap-row active':'gap-row'} onClick={()=>select(item)}><span><strong>#{item.id} · {GAP_SEVERITY_LABEL[item.severity]}</strong><small>{item.survey_area?.area_code??`AREA #${item.survey_area_id}`} · 期限 {GAP_DEADLINE_HOURS[item.severity]}h</small>{item.assignee&&<small>认领人：{item.assignee.display_name}</small>}</span><span><Chip size="small" label={GAP_STATE_LABEL[item.gap_state]} variant="outlined"/><Chip size="small" label={remain.text} color={remain.overdue?'error':remain.hours<1?'warning':'default'} sx={{mt:0.5}}/></span></button>})}{items.length===0&&<Typography variant="body2" color="text.secondary" sx={{p:2}}>{scope==='unclaimed'?'待认领池为空':scope==='mine'?'你还没有认领缺口':'暂无缺口快照'}</Typography>}</Box>
    <Box className="coverage-map"><Box className="section-heading"><Box><Typography variant="overline">SWATH / GAP / RESURVEY</Typography><Typography variant="h6">{selected?`缺口快照 #${selected.id}`:'等待覆盖计算'}</Typography></Box><Tooltip title="查看缺口 GeoJSON"><span><IconButton aria-label="查看缺口 GeoJSON" disabled={!selected} onClick={()=>setDrawer(true)}><DataObjectRounded/></IconButton></span></Tooltip></Box><SurveyCanvas layers={layers}/><MapLegend items={legends}/>{selected&&<><Box className="coverage-score"><div><span>覆盖率</span><strong>{(selected.coverage_ratio*100).toFixed(1)}%</strong></div><div><span>重叠率</span><strong>{(selected.overlap_ratio*100).toFixed(1)}%</strong></div><div><span>缺口率</span><strong>{(selected.gap_ratio*100).toFixed(1)}%</strong></div><div><span>处理耗时</span><strong>{selected.processing_millis} ms</strong></div></Box><Alert severity={deadline?.overdue?'error':selected.severity==='critical'?'error':'warning'} sx={{mt:2}}>{deadline&&<><strong>{deadline.text}</strong>（截止 {new Date(selected.due_at!).toLocaleString('zh-CN')}）：</>}{selected.explanation}</Alert>{evidence&&<Typography variant="caption" color="text.secondary" display="block" sx={{mt:1}}>{evidence.decision_boundary_note}</Typography>}</>}</Box>
    <Box className="review-pane"><Typography variant="overline">HUMAN DECISION</Typography><Typography variant="h6">人工复核</Typography>{selected?<><Box component="dl" className="evidence-list"><dt>状态</dt><dd>{GAP_STATE_LABEL[selected.gap_state]}</dd><dt>严重度</dt><dd>{GAP_SEVERITY_LABEL[selected.severity]}（{GAP_DEADLINE_HOURS[selected.severity]} 小时）</dd><dt>复核期限</dt><dd>{deadline?.text} · {new Date(selected.due_at??0).toLocaleString('zh-CN')}</dd><dt>认领人</dt><dd>{selected.assignee?selected.assignee.display_name:'待认领'}</dd><dt>算法版本</dt><dd>{selected.algorithm_version}</dd><dt>输入哈希</dt><dd className="hash">{selected.input_hash}</dd><dt>运行来源</dt><dd>{selected.source_run_ids.map(id=><RunStateBadge key={id} state={runs.find(run=>run.id===id)?.run_state??'processed'}/>)}</dd></Box>{canReview&&isUnclaimed&&<Button variant="contained" fullWidth sx={{mt:2}} onClick={()=>void claim(selected).then(()=>setScope('mine'))}>认领缺口（先到先得）</Button>}{canReview&&isMine&&!releaseOpen&&<Button variant="outlined" fullWidth size="small" sx={{mt:2}} onClick={()=>setReleaseOpen(true)}>退回待认领</Button>}{canReview&&isMine&&releaseOpen&&<Box sx={{mt:2}}><TextField multiline minRows={2} fullWidth size="small" label="退回原因（可选）" value={releaseNote} onChange={event=>setReleaseNote(event.target.value)}/><Stack direction="row" gap={1} sx={{mt:1}}><Button size="small" variant="outlined" color="inherit" onClick={()=>{setReleaseOpen(false);setReleaseNote('')}}>取消</Button><Button size="small" variant="contained" color="warning" onClick={()=>void confirmRelease()}>确认退回</Button></Stack></Box>}{canReview&&isMine&&(nextGapStates[selected.gap_state]?.length??0)>0&&<><TextField multiline minRows={3} fullWidth label="复核意见" value={note} onChange={event=>setNote(event.target.value)} sx={{mt:2}}/><Stack gap={1} sx={{mt:1.5}}>{nextGapStates[selected.gap_state]?.map(target=><Button key={target} variant={target==='false_positive'?'outlined':'contained'} onClick={()=>void transition(selected,target,note)}>{GAP_STATE_LABEL[target]}</Button>)}</Stack></>}{canReview&&!isMine&&selected.assignee&&<Typography variant="caption" color="text.secondary" sx={{mt:2,display:'block'}}>该缺口由 {selected.assignee.display_name} 认领，仅认领人可推进状态。</Typography>}</>:<Typography color="text.secondary" sx={{mt:1}}>运行一次覆盖计算后，可查看冻结哈希和人工决策状态。</Typography>}</Box></Box>
  <GeometryDetailDrawer open={drawer} onClose={()=>setDrawer(false)} title={selected?`覆盖缺口 #${selected.id}`:'覆盖缺口'} geometry={selected?.gap_geojson} metadata={selected?{'严重度':GAP_SEVERITY_LABEL[selected.severity],'覆盖率':`${(selected.coverage_ratio*100).toFixed(2)}%`,'算法版本':selected.algorithm_version,'输入哈希':selected.input_hash}:undefined}/>
  </>}
