import AssignmentIndOutlined from '@mui/icons-material/AssignmentIndOutlined'
import CalculateOutlined from '@mui/icons-material/CalculateOutlined'
import DataObjectRounded from '@mui/icons-material/DataObjectRounded'
import RefreshRounded from '@mui/icons-material/RefreshRounded'
import UndoRounded from '@mui/icons-material/UndoRounded'
import { Alert, Box, Button, Chip, FormControl, IconButton, InputLabel, LinearProgress, MenuItem, Select, Stack, TextField, Tooltip, Typography } from '@mui/material'
import { useEffect, useMemo, useState } from 'react'
import { GeometryDetailDrawer } from '../components/common/GeometryDetailDrawer'
import { MapLegend } from '../components/common/MapLegend'
import { PageHeader } from '../components/common/PageHeader'
import { RunStateBadge } from '../components/common/RunStateBadge'
import { SurveyCanvas } from '../components/common/SurveyCanvas'
import { useAuth } from '../hooks/useAuth'
import { useCoverageLayers } from '../hooks/useCoverageLayers'
import { useCoverageGapStore } from '../stores/coverage-gap-store'
import { useSonarRunStore } from '../stores/sonar-run-store'
import { useSurveyAreaStore } from '../stores/survey-area-store'
import type { GapClaimFilter } from '../types/coverage-gap'
import { GAP_SEVERITY_LABEL, GAP_SLA_LABEL, GAP_STATE_LABEL, type GapState } from '../types/enums/gap-severity'
import { deadlineView } from '../utils/deadline'

const nextGapStates:Partial<Record<GapState,GapState[]>>={detected:['reviewed'],reviewed:['accepted','false_positive'],accepted:['resurveyed'],false_positive:['closed'],resurveyed:['closed']}
const claimFilterOptions:{value:GapClaimFilter;label:string}[]=[{value:'all',label:'全部缺口'},{value:'unclaimed',label:'待认领'},{value:'claimed',label:'已认领'}]
export function CoveragePage(){const{hasRole,user}=useAuth();const areas=useSurveyAreaStore(state=>state.items);const fetchAreas=useSurveyAreaStore(state=>state.fetch);const runs=useSonarRunStore(state=>state.items);const fetchRuns=useSonarRunStore(state=>state.fetch);const{items,selected,evidence,loading,claimFilter,fetch,setClaimFilter,select,detect,claim,release,transition}=useCoverageGapStore();const[areaID,setAreaID]=useState(1);const[runIDs,setRunIDs]=useState<number[]>([1]);const[resolution,setResolution]=useState(20);const[drawer,setDrawer]=useState(false);const[note,setNote]=useState('已核对坐标系、输入校验和与补测线建议，结论仅用于离线规划。');const[claimNote,setClaimNote]=useState('');const[releaseReason,setReleaseReason]=useState('');useEffect(()=>{void Promise.all([fetch(),fetchAreas(),fetchRuns()])},[fetch,fetchAreas,fetchRuns]);useEffect(()=>{if(areas[0]&&!areas.some(area=>area.id===areaID))setAreaID(areas[0].id)},[areas,areaID]);useEffect(()=>{const eligible=runs.filter(run=>run.run_state==='processed'&&(run.transect_plan?.survey_area_id??0)===areaID).map(run=>run.id);if(eligible.length&&!runIDs.some(id=>eligible.includes(id)))setRunIDs([eligible[0]!])},[runs,areaID,runIDs]);const area=selected?.survey_area??areas.find(value=>value.id===(selected?.survey_area_id??areaID));const sourceRuns=selected?runs.filter(run=>selected.source_run_ids.includes(run.id)):runs.filter(run=>runIDs.includes(run.id));const plan=sourceRuns[0]?.transect_plan;const layers=useCoverageLayers(area,plan,sourceRuns,selected);const legends=useMemo(()=>layers.map(layer=>({label:layer.label,color:layer.color,pattern:layer.dash?'dash' as const:layer.fill?'fill' as const:'solid' as const})),[layers]);const calculate=async()=>detect({survey_area_id:areaID,source_run_ids:runIDs,algorithm_version:'grid-cover-v1.0.0',resolution_m:resolution});const eligibleRuns=runs.filter(run=>run.run_state==='processed'&&(run.transect_plan?.survey_area_id??0)===areaID);const canCalculate=hasRole('admin','data_processor');const canReview=hasRole('reviewer');const selectedDeadline=selected?deadlineView(selected):null;const mine=Boolean(selected&&user&&selected.claimed_by_id===user.id);const unclaimed=selected?.claimed_by_id==null;const closed=selected?.gap_state==='closed';return <>
  <PageHeader eyebrow="COVERAGE EVIDENCE REVIEW" title="覆盖分析" description="冻结测区与已处理航迹，计算覆盖、重复扫测和疑似缺口；待认领缺口按剩余期限排序，复核员先到先得。" actions={<Tooltip title="刷新"><IconButton aria-label="刷新覆盖结果" onClick={()=>void Promise.all([fetch(),fetchRuns()])}><RefreshRounded/></IconButton></Tooltip>}/>{loading&&<LinearProgress/>}
  <Box className="coverage-controls"><Box><Typography variant="overline">NEW ANALYSIS</Typography><Typography variant="h6">冻结本次输入</Typography></Box><FormControl size="small" sx={{minWidth:180}}><InputLabel>测区</InputLabel><Select label="测区" value={areaID} onChange={event=>{setAreaID(Number(event.target.value));setRunIDs([])}}>{areas.map(area=><MenuItem value={area.id} key={area.id}>{area.area_code}</MenuItem>)}</Select></FormControl><FormControl size="small" sx={{minWidth:220}}><InputLabel>已处理运行</InputLabel><Select multiple label="已处理运行" value={runIDs} onChange={event=>setRunIDs((event.target.value as number[]))}>{eligibleRuns.map(run=><MenuItem value={run.id} key={run.id}>{run.run_code}</MenuItem>)}</Select></FormControl><TextField size="small" type="number" label="网格 (m)" value={resolution} onChange={event=>setResolution(Number(event.target.value))} sx={{width:120}}/>{canCalculate&&<Button variant="contained" startIcon={<CalculateOutlined/>} disabled={runIDs.length===0} onClick={()=>void calculate()}>计算覆盖</Button>}</Box>
  <Box className="coverage-workspace"><Box className="result-rail"><Box className="section-heading"><Typography variant="h6">缺口队列</Typography><FormControl size="small" sx={{minWidth:110}}><Select value={claimFilter} onChange={event=>setClaimFilter(event.target.value as GapClaimFilter)} aria-label="认领筛选">{claimFilterOptions.map(option=><MenuItem value={option.value} key={option.value}>{option.label}</MenuItem>)}</Select></FormControl></Box><Typography variant="caption" color="text.secondary" sx={{px:1}}>待认领按剩余期限升序 · {items.length} 条</Typography>{items.map(item=>{const deadline=deadlineView(item);return <button type="button" key={item.id} className={selected?.id===item.id?'gap-row active':'gap-row'} onClick={()=>select(item)}><span><strong>#{item.id} · {GAP_SEVERITY_LABEL[item.severity]}</strong><small>{item.survey_area?.area_code??`AREA #${item.survey_area_id}`} · {item.algorithm_version}</small></span><span><Chip size="small" label={GAP_STATE_LABEL[item.gap_state]} variant="outlined"/>{item.gap_state!=='closed'&&<Chip size="small" color={deadline.overdue?'error':item.claimed_by_id==null?'warning':'default'} label={deadline.label}/>}<small>{item.claimed_by?`认领 ${item.claimed_by.display_name}`:'待认领'} · 期限 {GAP_SLA_LABEL[item.severity]}</small><small>缺口 {(item.gap_ratio*100).toFixed(1)}%</small></span></button>})}</Box>
    <Box className="coverage-map"><Box className="section-heading"><Box><Typography variant="overline">SWATH / GAP / RESURVEY</Typography><Typography variant="h6">{selected?`缺口快照 #${selected.id}`:'等待覆盖计算'}</Typography></Box><Tooltip title="查看缺口 GeoJSON"><span><IconButton aria-label="查看缺口 GeoJSON" disabled={!selected} onClick={()=>setDrawer(true)}><DataObjectRounded/></IconButton></span></Tooltip></Box><SurveyCanvas layers={layers}/><MapLegend items={legends}/>{selected&&<><Box className="coverage-score"><div><span>覆盖率</span><strong>{(selected.coverage_ratio*100).toFixed(1)}%</strong></div><div><span>重叠率</span><strong>{(selected.overlap_ratio*100).toFixed(1)}%</strong></div><div><span>缺口率</span><strong>{(selected.gap_ratio*100).toFixed(1)}%</strong></div><div><span>处理耗时</span><strong>{selected.processing_millis} ms</strong></div></Box><Alert severity={selected.severity==='critical'?'error':'warning'} sx={{mt:2}}>{selected.explanation}</Alert>{evidence&&<Typography variant="caption" color="text.secondary" display="block" sx={{mt:1}}>{evidence.decision_boundary_note}</Typography>}</>}</Box>
    <Box className="review-pane"><Typography variant="overline">HUMAN DECISION</Typography><Typography variant="h6">人工复核</Typography>{selected?<><Box component="dl" className="evidence-list"><dt>状态</dt><dd>{GAP_STATE_LABEL[selected.gap_state]}</dd><dt>严重度</dt><dd>{GAP_SEVERITY_LABEL[selected.severity]} · 期限 {GAP_SLA_LABEL[selected.severity]}</dd><dt>复核期限</dt><dd>{new Date(selected.deadline_at).toLocaleString()}{selectedDeadline&&!closed&&<Chip sx={{ml:1}} size="small" color={selectedDeadline.overdue?'error':'warning'} label={selectedDeadline.label}/>}</dd><dt>认领人</dt><dd>{selected.claimed_by?`${selected.claimed_by.display_name}（${selected.claimed_by.username}）`:'待认领'}</dd><dt>算法版本</dt><dd>{selected.algorithm_version}</dd><dt>输入哈希</dt><dd className="hash">{selected.input_hash}</dd><dt>运行来源</dt><dd>{selected.source_run_ids.map(id=><RunStateBadge key={id} state={runs.find(run=>run.id===id)?.run_state??'processed'}/>)}</dd></Box>
      {canReview&&unclaimed&&!closed&&<><TextField size="small" fullWidth label="认领备注（可选）" value={claimNote} onChange={event=>setClaimNote(event.target.value)} sx={{mt:1}}/><Button sx={{mt:1}} variant="contained" startIcon={<AssignmentIndOutlined/>} onClick={()=>void claim(selected,claimNote)}>认领此缺口</Button></>}
      {canReview&&mine&&!closed&&<><TextField size="small" fullWidth label="退回原因" value={releaseReason} onChange={event=>setReleaseReason(event.target.value)} sx={{mt:1}}/><Button sx={{mt:1}} variant="outlined" color="warning" startIcon={<UndoRounded/>} disabled={releaseReason.trim().length<4} onClick={()=>void release(selected,releaseReason)}>退回待认领</Button></>}
      {canReview&&!mine&&!unclaimed&&<Alert severity="info" sx={{mt:1}}>该缺口已由 {selected.claimed_by?.display_name??'其他复核员'} 认领，仅认领人可推进状态。</Alert>}
      {canReview&&mine&&(nextGapStates[selected.gap_state]?.length??0)>0&&<><TextField multiline minRows={3} fullWidth label="复核意见" value={note} onChange={event=>setNote(event.target.value)} sx={{mt:2}}/><Stack gap={1} sx={{mt:1.5}}>{nextGapStates[selected.gap_state]?.map(target=><Button key={target} variant={target==='false_positive'?'outlined':'contained'} onClick={()=>void transition(selected,target,note)}>{GAP_STATE_LABEL[target]}</Button>)}</Stack></>}
      {!canReview&&<Typography variant="caption" color="text.secondary" display="block" sx={{mt:1}}>仅复核员可认领并推进缺口状态。</Typography>}
    </>:<Typography color="text.secondary" sx={{mt:1}}>运行一次覆盖计算后，可查看冻结哈希和人工决策状态。</Typography>}</Box></Box>
  <GeometryDetailDrawer open={drawer} onClose={()=>setDrawer(false)} title={selected?`覆盖缺口 #${selected.id}`:'覆盖缺口'} geometry={selected?.gap_geojson} metadata={selected?{'严重度':GAP_SEVERITY_LABEL[selected.severity],'覆盖率':`${(selected.coverage_ratio*100).toFixed(2)}%`,'算法版本':selected.algorithm_version,'输入哈希':selected.input_hash}:undefined}/>
  </>}
